server:
  port: 0


spring:
  application:
    name: product-microservice
  # APACHE KAFKA CONFIGURATION - Producer
  kafka:
    producer:
      bootstrap-servers: # initial point to connect to the cluster
        - localhost:9092
        - localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # Key data type serializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # Value data type serializer
