server:
  port: 0


spring:
  application:
    name: product-microservice
  # APACHE KAFKA CONFIGURATION - Producer
  kafka:
    producer:
      acks: all # just wait acknowledgement from all servers
      retries: 10 # retry 10 times if unable to send message
      properties:
        retry.backoff.ms: 1000 # 1s interval after each retry
      bootstrap-servers: # initial point to connect to the cluster
        - localhost:9092
        - localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # Key data type serializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # Value data type serializer
